# Use an official Python runtime as the base image
FROM python:3.7-slim

# Set the working directory in the container to /Hello_world
WORKDIR /Hello_world

# Add the current directory contents into the container at /Hello_world
ADD . /Hello_world

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Run app.py when the container launches
CMD ["python", "Hello_world.py"]
